export interface PluginSurface {
  id: string;
  title: string;
  summary: string;
  bullets: string[];
  tagline?: string;
  apiSymbols: string[];
  firstParty?: string[];
  experimental?: boolean;
}

export interface SurfaceGroup {
  id:
    | "app-shell"
    | "command-palette"
    | "composer"
    | "home"
    | "settings"
    | "extensions"
    | "headless";
  title: string;
  blurb: string;
  fixtureKind: "spatial" | "capability-grid";
  surfaces: PluginSurface[];
  sections?: readonly {
    title: string;
    surfaceIds: readonly string[];
  }[];
}

export type FixtureResponsiveStrategy = "scale-together" | "reflow";

export function fixtureResponsiveStrategy(
  group: Pick<SurfaceGroup, "fixtureKind">,
): FixtureResponsiveStrategy {
  return group.fixtureKind === "spatial" ? "scale-together" : "reflow";
}

export const SURFACE_GROUPS: SurfaceGroup[] = [
  {
    id: "app-shell",
    title: "The bb app window",
    fixtureKind: "spatial",
    blurb:
      "The main bb window, containing the sidebar, the conversation, and the side panel. A plugin can add rows, controls, panel tabs, and message content to the numbered regions.",
    surfaces: [
      {
        id: "sidebar-navigation",
        title: "Sidebar navigation",
        summary:
          "Replaces bb's navigation controls above the thread list with a component your plugin renders. With this, a plugin can:",
        bullets: [
          "Arrange New thread, Search, Plugins, Skills, and plugin destinations, in the user's saved order with hidden items flagged",
          "Activate each destination through bb, including split placement and a split mini-map for supported items",
          "Hide, show, and reorder destinations, open bb's customize editor, and open or disable the plugin behind a panel",
          "Draw bb's icons and plugin branding, and each panel's live sidebar accessory",
          "Put controls, such as navigation icons, in the header row beside the sidebar toggle with experimental_sidebarHeader, and have the navigation slot render nothing while that header is mounted",
          "Start from bb's own rows: they ship as the bundled Navigation plugin, which uses only this API",
          "Leave the thread list, footer, drawer, and resize handle under bb's control",
        ],
        apiSymbols: [
          "ExperimentalSidebarNavigationRegistration",
          "ExperimentalSidebarNavigationProps",
          "experimental_useSidebarNavigation",
          "ExperimentalSidebarNavigationState",
          "ExperimentalSidebarNavigationItem",
          "ExperimentalSidebarNavigationAction",
          "ExperimentalSidebarNavigationActions",
          "ExperimentalSidebarNavigationIcon",
          "experimental_SidebarNavigationIcon",
          "ExperimentalSidebarNavigationIconProps",
          "ExperimentalSidebarNavigationShortcut",
          "ExperimentalSidebarNavigationActivationOptions",
          "experimental_useSidebarNavigationSplit",
          "ExperimentalSidebarNavigationSplit",
          "ExperimentalSidebarNavigationSplitOptions",
          "ExperimentalSidebarHeaderRegistration",
          "ExperimentalSidebarHeaderProps",
        ],
        firstParty: ["Navigation"],
        experimental: true,
      },
      {
        id: "nav-panel",
        title: "Full-page panels",
        summary:
          "Adds a row to bb's sidebar that opens a page your plugin renders where threads normally appear. With this, a plugin can:",
        bullets: [
          "Render any React you write across that whole area",
          "Give the panel and each fixed tab their own icons; resolved names override plugin branding in navigation, headers, and tabs",
          "Get its own URL, so the page can be linked to and bb's back and forward buttons work",
          "Register ordered, non-closable fixed tabs beside Browser and Terminal; bb persists selection and mounts each component only while its tab is visible in an open pane",
          "Open an owned fixed tab with experimental_useAppPanel and read its validated JSON target with experimental_useFixedTabTarget; targets survive route changes in the current session, but not a refresh",
          "Add headerContent to the page title bar, or a non-interactive experimental_sidebarAccessory to the desktop sidebar row",
        ],
        apiSymbols: [
          "PluginNavPanelRegistration",
          "PluginNavPanelProps",
          "PluginFixedTabRegistration",
          "PluginFixedTabDeclaration",
          "ExperimentalPluginFixedTabReference",
          "ExperimentalFixedTabTargetContract",
          "experimental_useAppPanel",
          "ExperimentalAppPanel",
          "ExperimentalOpenFixedTabOptions",
          "experimental_useFixedTabTarget",
          "ExperimentalFixedTabTargetState",
          "useBbContext",
          "useBbNavigate",
          "BbNavigate.toPluginPanel",
        ],
        firstParty: ["Automations", "Docs", "GitHub", "Tasks"],
      },
      {
        id: "thread-row-status",
        title: "Thread row status",
        summary:
          "A small status bb can draw on a thread's row in the sidebar. With this, a plugin can:",
        bullets: [
          "Give the status an icon and a label",
          "Mark a thread as running while it works on it, and bb shimmers the icon",
          "Mark it succeeded or failed when the work ends, and bb settles the icon",
          "Set it only from an [app-wide script](content-scripts). A status needs an owner that outlives any single screen, and those scripts are the only plugin code that does",
          "Rely on bb to clear it when the script unmounts",
        ],
        apiSymbols: [
          "PluginComposerThreadRowStatus",
          "PluginContentScriptContext",
        ],
        experimental: true,
      },
      {
        id: "thread-list",
        title: "The thread list",
        summary:
          "Replaces the list of threads in bb's sidebar with a component your plugin renders. With this, a plugin can:",
        bullets: [
          "Render every row, and decide the grouping, the ordering, and what each row shows",
          "Read live thread, section, project, and run-status data; select active or archived threads with experimental_lifecycles and load more archived pages through experimental_archived",
          "Use host-owned actions for navigation, pinning, read state, renaming, archiving, and deletion confirmation; opt into per-row pull-request state and drag-to-split support",
          "Archiving includes child threads and follows Settings → General → Thread archive confirmation; the archive toast offers Undo",
          "Open the root new-thread composer with a project, section, existing environment, or machine selected through hostId; an existing environment takes priority over a machine",
          "Read normalized checks, review, and mergeability states through experimental_checks, experimental_review, and experimental_mergeability. experimental_autoMerge reports auto-merge; experimental_inMergeQueue is null if the queue lookup failed. Attention distinguishes failures, queued PRs, reviews, pending checks, generic blocking, and ready-to-merge PRs without plugin GitHub polling.",
          "Own the whole region: by default bb shows the first installed thread list other than the bundled Thread list plugin, users can pin one in Settings → Appearance → Sidebar, and the sidebar shows a placeholder until the list mounts; the deprecated searchQuery is always empty because the quick palette owns thread search",
          "Pass experimental_placement to openNewThread to select sectionId and pinned explicitly. Omission clears previous composer placement; the legacy sectionId option remains supported.",
          "Replace only the list. The New thread button, the search action, the plugin rows, and the sidebar footer stay bb's",
          "Key state kept in the browser, such as a localStorage mirror, with experimental_usePluginId, so a copy published under another name keeps its own",
        ],
        apiSymbols: [
          "PluginThreadListRegistration",
          "PluginThreadListProps",
          "experimental_useSidebarThreads",
          "PluginSidebarThreadsState.experimental_archived",
          "PluginSidebarThreadsState.experimental_hosts",
          "PluginSidebarThreadsState",
          "PluginSidebarThread",
          "PluginSidebarSection",
          "experimental_useSidebarThreadActions",
          "PluginSidebarThreadActions",
          "PluginSidebarThreadActions.openNewThread",
          "PluginSidebarThreadActions.openNewThread.experimental_placement",
          "experimental_useSidebarThreadPullRequest",
          "PluginSidebarThreadPullRequestState",
          "PluginSidebarPullRequest.experimental_autoMerge",
          "PluginSidebarPullRequest.experimental_inMergeQueue",
          "PluginSidebarPullRequest.experimental_checks",
          "PluginSidebarPullRequest.experimental_review",
          "PluginSidebarPullRequest.experimental_mergeability",
          "experimental_useSidebarThreadSplit",
          "PluginSidebarThreadSplit",
          "useSidebarThreadDraft",
          "PluginSidebarThreadDraftState",
          "useSidebarThreadDraftIds",
          "useSidebarThreadRowStatus",
          "useSidebarThreadRowStatuses",
          "PluginSidebarThreadRowStatus",
          "useSidebarSplitLayout",
          "PluginSidebarSplitLayout",
          "useSidebarThreadShortcut",
          "PluginSidebarThreadShortcut",
          "ThreadTitle",
          "PluginThreadTitleProps",
          "useEnvironmentProviders",
          "PluginEnvironmentProvidersState",
          "useSdk",
          "PluginBrowserBbSdk",
          "experimental_usePluginId",
        ],
        experimental: true,
      },
      {
        id: "sidebar-footer",
        title: "Sidebar footer items",
        summary:
          "Adds a host-rendered icon item to the bottom of bb's sidebar. With this, a plugin can:",
        bullets: [
          "Run an action, or reveal plugin-rendered content above the footer row",
          "Let bb coordinate one open disclosure across every enabled plugin",
          "Respect user ordering and visibility in Appearance; hidden actions and disclosures remain usable from More",
          "Keep navigation, tabs, data, and controls inside the plugin's disclosure component",
        ],
        apiSymbols: [
          "ExperimentalSidebarFooter",
          "ExperimentalSidebarFooterItemBase",
          "ExperimentalSidebarFooterItemRegistration",
          "ExperimentalSidebarFooterActionRegistration",
          "ExperimentalSidebarFooterActionContext",
          "ExperimentalSidebarFooterDisclosureRegistration",
          "ExperimentalSidebarFooterDisclosureProps",
          "ExperimentalSidebarFooterDisclosureController",
          "PluginSidebarFooterActionRegistration",
        ],
        firstParty: ["Provider usage"],
        experimental: true,
      },
      {
        id: "thread-header",
        title: "Thread header controls",
        summary:
          "Adds a control to the header bar at the top of an open thread. With this, a plugin can:",
        bullets: [
          "Render a React component rather than a plain button, so it can show live state",
          "Receive the id of the thread currently on screen",
          "Render in the same row as bb's own header controls",
        ],
        apiSymbols: ["PluginThreadHeaderActionRegistration"],
        experimental: true,
      },
      {
        id: "timeline-renderers",
        title: "Timeline entry content",
        summary:
          "Renders the expanded content of plugin-owned timeline entries while bb keeps each entry's header and controls. With this, a plugin can:",
        bullets: [
          "Draw the expanded content beneath timeline entries created by the plugin's own provider",
          "Receive the entry data and plugin payload, plus bb's default content as `Original`",
          "Fall back to bb's default content automatically when the plugin is unavailable or crashes",
        ],
        apiSymbols: [
          "PluginTimelineRendererRegistration",
          "PluginTimelineRendererProps",
        ],
        experimental: true,
      },
      {
        id: "message-directives",
        title: "Rich message embeds",
        summary:
          "Renders your component inside an agent's reply, in place of a marker the agent writes into its message. With this, a plugin can:",
        bullets: [
          "Claim a directive name; an agent writes `::name` in a message to invoke it",
          "Replace that marker with a live component, inline in the conversation",
          "Open a file from the workspace when someone interacts with the embed",
        ],
        apiSymbols: ["PluginMessageDirectiveRegistration"],
        firstParty: ["Docs", "Inline visualizations", "Tasks", "Workflows"],
      },
      {
        id: "message-actions",
        title: "Message actions",
        summary:
          "Adds an action to individual messages in a thread. With this, a plugin can:",
        bullets: [
          "Appear in the row that shows under messages on hover, or in the toolbar that appears when text in an agent's message is selected",
          "Receive the message, plus the selected text when the action was run from a selection",
          "Show the action’s explicit icon wherever it appears, with plugin branding as the fallback for omitted or unknown names",
          "Open one of the plugin's own [side-panel tabs](thread-panel) with what it received",
          "Write into the composer of the message's thread through the same composer handle useComposer() returns",
        ],
        apiSymbols: [
          "PluginMessageActionRegistration",
          "PluginMessageActionContext",
        ],
        firstParty: ["Side chat"],
      },
      {
        id: "pending-interaction",
        title: "In-thread forms",
        summary:
          "Asks the person a question in the thread composer and delivers their answer to the agent, even if the original turn has ended. With this, a plugin can:",
        bullets: [
          "Replace the prompt box with a form the plugin draws, even after the agent's turn has ended",
          "Receive the submitted answer, or a cancellation and its reason",
          "Leave a row in the thread timeline: the plugin names its header and describes what a submission shows, so the transcript keeps exactly what the plugin chooses",
          "Show bb's answer shortcuts next to each option and act when the person presses one, with experimental_useQuestionFormHost",
        ],
        apiSymbols: [
          "PluginUi",
          "PluginInteractionRequest",
          "PluginInteractionDescription",
          "PluginRowPresentation",
          "PluginPendingInteractionRegistration",
          "experimental_useQuestionFormHost",
        ],
        firstParty: ["Ask User Question", "Secrets"],
      },
      {
        id: "code-renderers",
        title: "Code & diff renderers",
        summary:
          "Replaces bb's source-code or diff renderer everywhere that kind of content appears. With this, a plugin can:",
        bullets: [
          "Register the source-code and diff replacements independently",
          "Apply each replacement across bb's file previews, timeline and environment diffs, and plugin pages",
          "Hand any individual render back to bb's built-in renderer, and fall back to it automatically if the plugin is unavailable or crashes",
        ],
        apiSymbols: [
          "PluginSourceCodeRendererRegistration",
          "PluginSourceCodeRendererProps",
          "PluginDiffRendererRegistration",
          "PluginDiffRendererProps",
        ],
        experimental: true,
      },
      {
        id: "browser-toolbar",
        title: "Browser toolbar controls",
        summary:
          "Adds a plugin control to the toolbar of each open Browser tab. With this, a plugin can:",
        bullets: [
          "Act on the Browser tab currently in front of the user",
          "Receive the owning thread id, tab id, and current URL",
          "Render beside the Browser address bar and native controls",
          "Use experimental_page on desktop to run scripts and receive messages without a CDP lease; it is null in the web app",
          "Evaluate in an isolated world by default, with bb.postMessage for replies; the main world shares page globals and has no message bridge. Navigation removes installed scripts",
        ],
        apiSymbols: [
          "ExperimentalPluginBrowserToolbarActionRegistration",
          "ExperimentalPluginBrowserToolbarActionProps",
          "ExperimentalPluginBrowserPage",
          "ExperimentalPluginBrowserPageEvaluateOptions",
          "ExperimentalPluginBrowserPageWorld",
        ],
        experimental: true,
      },
      {
        id: "thread-panel",
        title: "Thread side-panel tabs",
        summary:
          "Adds a tab to the side panel that opens to the right of a thread. With this, a plugin can:",
        bullets: [
          "Render the tab's contents and receive the id of the thread it was opened from",
          "Show the action’s explicit icon in the launcher and opened tab; omitted or unknown names fall back to plugin branding",
          "Open the tab from a [message action](message-actions), from the + button in the side panel, or from its own code",
        ],
        apiSymbols: ["PluginThreadPanelActionRegistration"],
        firstParty: ["Docs", "GitHub", "Side chat", "Tasks", "Workflows"],
      },
      {
        id: "file-opener",
        title: "File viewers & editors",
        summary:
          "Registers a viewer for the file types you name, so bb opens those files there instead of its built-in preview. With this, a plugin can:",
        bullets: [
          "Declare the file extensions it handles, for example `.csv` or `.excalidraw`",
          "Render its own viewer or editor whenever a file of that type is opened in bb",
          "Receive the file path and source: workspace paths are relative to the environment, thread-storage paths to the storage root, and host paths are absolute; project workspace sources can carry experimental_hostId",
          "Render Original to delegate an individual file to bb's built-in preview",
          "Reveal linked lines with experimental_lineRange, including repeated targets in an already open editor",
        ],
        apiSymbols: [
          "PluginFileOpenerRegistration",
          "PluginFileOpenerProps",
          "PluginFileOpenerSource",
        ],
        firstParty: ["Docs", "File Editor"],
      },
      {
        id: "app-overlay",
        title: "App-wide overlays",
        summary:
          "Mounts floating plugin UI across the bb app, outside route-owned layout regions. With this, a plugin can:",
        bullets: [
          "Render a persistent widget once per bb window while the plugin is enabled",
          "Use app-level SDK hooks and preserve their React context through portals",
          "Own the widget's chrome, position, visibility, and responsive behavior",
          "Coexist with other overlays while crashes remain isolated to the overlay that failed",
        ],
        apiSymbols: [
          "ExperimentalAppOverlayRegistration",
          "ExperimentalAppOverlayProps",
        ],
        experimental: true,
      },
      {
        id: "content-scripts",
        title: "App-wide scripts",
        summary:
          "Runs your code inside the bb window itself, without rendering a UI of its own. With this, a plugin can:",
        bullets: [
          "Mount once per bb window and unmount when the window reloads",
          "Add behavior that is not tied to one screen, such as a keyboard shortcut",
          "Set a [thread row status](thread-row-status) on any thread, for as long as the script is mounted",
          "Add plugin-owned elements to app pages without taking ownership of bb's built-in layout",
          "Return a cleanup function. bb calls it once on unmount, and clears any row statuses the script set",
        ],
        apiSymbols: [
          "PluginContentScriptRegistration",
          "PluginContentScriptContext",
        ],
      },
    ],
  },
  {
    id: "command-palette",
    title: "Command palette",
    fixtureKind: "spatial",
    blurb:
      "bb's searchable command menu. A plugin can add actions that match, rank, and run alongside bb's own commands.",
    surfaces: [
      {
        id: "command-palette-actions",
        title: "Command palette actions",
        summary:
          "Registers a command with app.commands.register and adds a row under Plugins in bb's quick command palette. With this, a plugin can:",
        bullets: [
          "Supply the row's label and run behavior; bb owns matching, ordering, and recency",
          "Offer a defaultShortcut with key and optional mod, meta, control, alt, and shift modifiers; mod means Command on macOS and Control elsewhere",
          "Let users bind or rebind every command in Keyboard Settings; conflicts offer Replace binding or Cancel, and conflicting plugin defaults stay unbound",
          "Keep saved bindings across reloads and disable/re-enable using plugin:<plugin-id>/<command-id>; palette and keyboard invocation share availability and error handling",
          "Migrate slots.commandPaletteAction to commands.register with the same fields; the old method remains a deprecated alias",
          "Read the current thread and project, and hide the row when it is unavailable",
          "Open one of the plugin's own thread side-panel tabs when a thread is on screen",
        ],
        apiSymbols: [
          "PluginAppBuilder.commands",
          "PluginAppCommands",
          "PluginCommandRegistration",
          "PluginCommandContext",
          "PluginCommandShortcut",
        ],
      },
    ],
  },
  {
    id: "composer",
    title: "The composer",
    fixtureKind: "spatial",
    blurb:
      "The prompt box used to start a thread and to reply inside one. A plugin can add banners, menu entries, and action buttons to it, answer mention searches, highlight the draft prompt, and supply the agent that runs the message.",
    surfaces: [
      {
        id: "composer-banners",
        title: "Banners",
        summary:
          "Renders a banner above the prompt box. With this, a plugin can:",
        bullets: [
          "Render its own component in the strip directly above the draft prompt",
          "Choose the new-thread, thread, or queued-message composer scopes; omit scopes to appear in all of them",
          "Use the default card chrome or select bare chrome to own the banner's presentation",
          "Show something the person should read before sending, such as a warning or a status",
        ],
        apiSymbols: ["ComposerCustomization", "PluginComposerScope"],
        firstParty: ["Provider retry", "Workflows"],
      },
      {
        id: "composer-state",
        title: "Draft prompt state & locking",
        summary:
          "Reads the draft prompt, and can block typing while the plugin works. With this, a plugin can:",
        bullets: [
          "Read the draft prompt's text and every @-mention in it, whether it is empty, and how many files are attached",
          "Read draft.attachments and atomically restore text, mention pills, and uploaded attachments with replace; omit attachments to preserve them or pass an empty array to clear them. Attachment sizeBytes is absent when unknown. Preserve sourceProjectId on references from uploads and prompt history: core previews from the source and copies files to the destination project when submitted, without a plugin copy request. Absolute paths from history carry hostId instead; core rejects them in a thread on another machine",
          "Use insert(parts, { at: cursor or end }) to add text and pills; use replace(current => next) for atomic transformations of the latest immutable text, mentions, and attachments",
          "Insert a thread pill with a thread mention containing kind: thread, threadId, projectId, and label. User-pasted same-origin thread URLs resolve into that same mention; insert and replace keep programmatic URL text literal",
          "Supply explicit mention ranges to replace: it does not infer or rebase pills from text edits; returning the current snapshot is a no-op, and throwing or returning invalid data leaves the draft unchanged",
          "Core quotes use replace to append blockquoted text and merge attachments by path, then focus; attachments belong to the draft, not to the quoted block",
          "Migrate setText and updateText to replace with explicit mentions, clear to replace({ text: empty string, mentions: [] }), insertMention to insert(..., { at: end }) plus focus, and addQuote/removeMention to replacement transforms; setText/updateText/clear/addQuote/insertMention/removeMention are runtime-only compatibility paths absent from published types",
          "Core prefills and prompt history use these same replacement operations; submission rollback and restore-if-empty initialization remain internal safeguards",

          "Read the prompt box's layout, whether the thread is running a turn, whether the composer is submitting, and whether submitting is blocked with the same reason bb's send button shows",
          "Keep one stable composer handle across renders and async work; writes after the composer leaves the screen still land in its saved draft",
          "List every composer on screen from a panel or page, label each by its scope, and write into the one the user picks",
          "Lock the input and release it again, so the draft prompt cannot change mid-operation",
          "Release locks and text effects automatically when the slot unmounts or its composer scope changes; persistent [thread row status](thread-row-status) requires an app-wide script",
        ],
        apiSymbols: [
          "useComposer",
          "useComposers",
          "PluginComposerApi",
          "ComposerDraft",
          "ComposerDraftReplacement",
          "ComposerAttachment",
          "PluginComposerApi.replace",
          "ComposerDraftSnapshot",
          "PluginComposerApi.insert",
          "ComposerMention",
        ],
      },
      {
        id: "mention-provider",
        title: "Mentions",
        summary:
          "Adds results to the menu that opens when someone types a trigger character in the prompt box. On a trigger bb does not use itself, your plugin opens that menu and owns it. With this, a plugin can:",
        bullets: [
          "Answer each keystroke after the trigger with a list of items to show",
          "Give each item a built-in or registered icon that takes precedence over plugin branding in the menu, composer, and sent messages; omitted or unknown names fall back to plugin branding, then the generic plugin icon",
          "Claim one or more of the trigger characters @, #, $, !, and ~. Omit them to answer the default @",
          "Turn a picked item into a chip in the draft prompt, and resolve its content once per unique mention when the message is sent; a resolution failure blocks sending",
        ],
        apiSymbols: [
          "PluginMentionProviderRegistration",
          "PluginMentionSearchContext",
          "PluginMentionItem",
        ],
        firstParty: ["Docs", "GitHub", "Tasks"],
      },
      {
        id: "composer-rich-text",
        title: "Draft prompt highlighting",
        summary:
          "Styles text ranges as the person types a prompt, without changing the text. With this, a plugin can:",
        bullets: [
          "Match ranges in the draft prompt, such as a ticket number or the word TODO",
          "Change only how those ranges look; the text the agent receives is untouched",
          "Re-run its matcher on every keystroke",
          "Remove a plugin-owned mention from the draft, including its visible text",
          "Respond after a local message is successfully sent or queued; failed sends do not notify",
        ],
        apiSymbols: [
          "ComposerRichTextSpec",
          "PluginComposerApi.replace",
          "PluginComposerApi.onSubmitted",
        ],
      },
      {
        id: "composer-plus-menu",
        title: "The + and send menus",
        summary:
          "Adds rows to the menu that opens from the + button beside the prompt box, or to the menu beside the send button. With this, a plugin can:",
        bullets: [
          "Supply each row's icon, label, and disabled state; bb renders the row itself",
          "Run a callback when someone picks the row",
          "Read and rewrite the draft prompt from that callback",
          "Send the draft at a time the person picks, through the prompt box's own send — so a scheduled message keeps its attachments, its @-mentions, and on the new-thread screen the agent and environment chosen on screen",
          "Submit the draft with plugin-owned JSON that its dispatch hook can interpret and use to queue the message; submitting waits for uploads and otherwise refuses exactly when bb's send button would",
          "Add the same kind of row to the menu beside the send button, shown only while the composer can submit",
        ],
        apiSymbols: [
          "ComposerPlusMenuItem",
          "ComposerSendMenuItem",
          "ComposerSubmitOptions",
        ],
        firstParty: ["Drafts", "Send later"],
      },
      {
        id: "provider-picker",
        title: "Agent providers",
        summary:
          "Adds an agent to bb's model picker and runs the threads started with it. With this, a plugin can:",
        bullets: [
          "Appear in the model picker beside bb's built-in providers",
          'Declare bb.experimental_providers: [{ kind: "agent", id, displayName }] in package.json to keep agent providers discoverable in Settings → Providers before the plugin runs. Runtime registration remains authoritative; metadata does not register an executable provider. Core enable/disable preferences preserve other providers from the same plugin',
          "Declare what the provider supports, then serve its model list at runtime",
          "Declare serviceTiers with non-empty tier IDs, labels, and descriptions. AvailableModel.supportedServiceTiers narrows that vocabulary per model: omitted uses the provider list, an empty array offers no tiers, and entries may override labels and descriptions. The reserved default tier means standard execution; other selected IDs reach the bridge as serviceTier",
          "Supply a small icon that appears next to its name; React icon overrides require providerKind and providerId",
          "Publish context snapshots through contextWindow deltas, with provider-defined category IDs and labels. Each category declares used, free, reserved, or deferred accounting; entries are included in its total and may be partial. Snapshots include capture time, session identity, model, totals, and an optional auto-compaction threshold",
          "Receive every message in a thread started with it, through a bridge process the plugin ships",
          "Launch and stop the provider's CLI from that bridge with bb's portable launcher, which runs npm .cmd shims and ends the whole process tree on Windows",
          "Handle provider/installation/status with checkUpdates: false using local executable and version checks only, preserving operation-specific minimum versions; omitted or true keeps full install-source and update discovery for Settings",
          "Contribute validated environment variables to any provider for each session and turn",
        ],
        apiSymbols: [
          "contextSnapshotSchema",
          "ContextSnapshot",
          "ContextCategory",
          "ContextEntry",
          "PluginProviderDeclaration",
          "AvailableModel",
          "ModelServiceTier",
          "providerInstallationStatusParamsSchema",
          "ProviderInstallationStatusParams",
          "PluginProviderIconRegistration",
          "experimental_useProviders",
          "PluginProvidersState",
          "ExperimentalPluginProviderEnvContext",
          "ExperimentalPluginProviderEnvEntry",
          "ExperimentalPluginProviderEnvHealthContext",
          "ExperimentalPluginProviderEnvHealth",
          "experimental_spawnPortableProcess",
          "experimental_killPortableProcess",
        ],
        firstParty: [
          "ACP providers",
          "Claude Code provider",
          "Codex provider",
          "Pi provider",
        ],
        experimental: true,
      },
      {
        id: "composer-actions",
        title: "Inline actions",
        summary:
          "Adds a button to the row of controls inside the prompt box, beside the voice and send buttons. With this, a plugin can:",
        bullets: [
          "Read and rewrite the draft prompt, for example rephrasing it or inserting a template",
          "Insert text and @-mentions at the cursor or at the end, optionally as their own paragraph; a mention read from the draft is recreated exactly, and the plugin's own mentions resolve fresh context when the message is sent",
          "Lock the input while it works, and tint the whole draft while it does",
          "Open a registered popup sharing the mention menu's above/below placement; compact interactive popups use bb's responsive drawer",
          "Register a rebindable composer command that runs in the composer holding the caret, for example to open the popup with Ctrl+R; inside the popup, useComposer targets that composer and useComposer().experimental_closePopup() restores editor focus",
          "Read reactive picker values from composer.selection, or set them through the same paths the pickers use and read back what the composer settled on",
          "Render in the same row as bb's own prompt-box buttons; bb keeps up to 3 plugins with applicable actions inline, ranked by use, and moves the rest into an overflow menu",
        ],
        apiSymbols: [
          "PluginComposerApi",
          "PluginComposerApi.insert",
          "ComposerInsertPart",
          "ComposerInsertOptions",
          "ComposerCustomization.experimental_popups",
          "ExperimentalComposerPopupRegistration",
          "PluginComposerApi.experimental_openPopup",
          "PluginComposerApi.experimental_closePopup",
          "PluginAppComposer.experimental_registerCommand",
          "ExperimentalComposerCommandRegistration",
          "PluginComposerApi.setSelection",
          "PluginComposerApi.selection",
          "ComposerSelection",
        ],
      },
    ],
  },
  {
    id: "home",
    title: "Home page",
    fixtureKind: "spatial",
    blurb:
      "The screen bb opens on, holding the new-thread composer and a side panel. A plugin can add a section below the composer, and an action in that panel that opens its own tab.",
    surfaces: [
      {
        id: "homepage-section",
        title: "Home-screen sections",
        summary:
          "Adds a full-width section to bb's home page: below the composer on desktop, or in the scrollable content above it on mobile. With this, a plugin can:",
        bullets: [
          "Render its own component across the width of the content area",
          "Render before any thread exists, which suits shortcuts and pinned work",
          "Render after bb's own content, in the order plugins registered",
        ],
        apiSymbols: ["PluginHomepageSectionRegistration"],
      },
      {
        id: "new-thread-panel",
        title: "New-thread side panel",
        summary:
          "Adds a plugin tab to the side panel on the new-thread screen. With this, a plugin can:",
        bullets: [
          "Render before a thread exists, so it receives no thread id",
          "Host setup the person does while writing the first prompt",
          "Show the action’s explicit icon in the launcher and opened tab; omitted or unknown names fall back to plugin branding",
          "Receive the project selected in the prompt box",
        ],
        apiSymbols: ["PluginNewThreadPanelActionRegistration"],
        experimental: true,
      },
    ],
  },
  {
    id: "settings",
    title: "Plugin settings page",
    fixtureKind: "spatial",
    blurb:
      "The settings page bb creates for every installed plugin. A plugin can declare fields for bb to render and add its own section below them.",
    surfaces: [
      {
        id: "declarative-settings",
        title: "Settings fields",
        summary:
          "Declares the settings your plugin needs as plain data; bb renders the form for them on the plugin's settings page and stores the values. With this, a plugin can:",
        bullets: [
          "Declare each field's type (text, number, toggle, choice, or project) with a label and an optional default",
          "Get the form, its validation, and autosaving without writing any UI",
          "Validate each proposed value with a synchronous, non-transforming Standard Schema through `experimental_schema`; Zod schemas qualify",
          "Render multi-line text with `experimental_multiline`",
          "Mark a text field secret: bb stores it in a protected file on the server and never sends it to the browser",
          "Read values from server code, update them with `experimental_set`, or read non-secret values from plugin UI with `useSettings()`",
        ],
        apiSymbols: [
          "PluginSettings",
          "PluginSettingsHandle",
          "PluginSettingDescriptor",
          "PluginSettingsState",
        ],
        firstParty: [
          "Custom instructions",
          "GitHub",
          "Provider retry",
          "Workflows",
        ],
      },
      {
        id: "settings-section",
        title: "Custom settings section",
        summary:
          "Renders your own React component on the plugin's settings page, below the [fields bb generated](declarative-settings). Use it for anything that is not a value in a form. With this, a plugin can:",
        bullets: [
          "Set experimental_page: mobile to render on Mobile settings only when your plugin owns the selected access provider, such as connected phone-pairing controls",
          "Render whatever UI it needs, such as a connect-account button, a test-connection result, or a preview",
          "Run in the browser, so it stores nothing itself. It calls the plugin's own backend to do that",
          "Supply a heading and a one-line description for bb to render above it",
        ],
        apiSymbols: [
          "PluginSettingsSectionRegistration.experimental_page",
          "PluginSettingsSectionRegistration",
        ],
        firstParty: [
          "Account Pooler [Experimental]",
          "Keep Awake",
          "Memory",
          "bb connect",
        ],
      },
    ],
  },
  {
    id: "extensions",
    title: "Plugin page",
    fixtureKind: "spatial",
    blurb:
      "The page bb shows for an installed plugin under Plugins: what it is, what it registers, and whether it is healthy. A plugin can report that it needs configuring, and bb says so at the top of this page.",
    surfaces: [
      {
        id: "plugin-status",
        title: "Configuration status",
        summary:
          "Reports that the plugin cannot run until someone configures it, so bb can say so instead of the plugin failing silently. With this, a plugin can:",
        bullets: [
          "Set a needs-configuration state with a message naming what is missing",
          "Show a warning banner with that message on the plugin's page",
          "Send users to Settings when the plugin declares configuration fields; bb reloads the plugin after they save",
        ],
        apiSymbols: ["PluginStatusApi"],
        firstParty: ["GitHub", "Workflows"],
      },
    ],
  },
  {
    id: "headless",
    title: "Plugin backend",
    fixtureKind: "capability-grid",
    blurb: "The parts of the plugin API with no interface of their own.",
    sections: [
      {
        title: "Commands & agent capabilities",
        surfaceIds: ["cli", "agent-tools"],
      },
      {
        title: "Running & reacting",
        surfaceIds: [
          "background",
          "wire",
          "thread-events",
          "dispatch-hook",
          "environment-providers",
          "machine-providers",
          "server-access",
          "host-workers",
        ],
      },
      {
        title: "Data & platform",
        surfaceIds: [
          "storage",
          "bb-sdk",
          "thread-plugin-metadata",
          "desktop-browsers",
          "ai-services",
          "host-components",
        ],
      },
      {
        title: "Confidence",
        surfaceIds: ["testing"],
      },
    ],
    surfaces: [
      {
        id: "cli",
        tagline: "Your own `bb <name>` command",
        title: "bb CLI commands",
        summary:
          "Registers a top-level `bb <name>` command, available in the terminal and to agents. With this, a plugin can:",
        bullets: [
          "Be invoked the same way by a person at a terminal and by an agent mid-task",
          "Receive the thread and project it was invoked from, when bb knows them",
          "Make the plugin usable from scripts and automations, not only from the UI",
          "Declare commands, arguments and options once and get parsing, `--help`, nearest-name suggestions and JSON errors",
        ],
        apiSymbols: [
          "PluginCli",
          "PluginCliResult",
          "defineCli",
          "cliCommand",
          "PluginCliError",
          "PluginCliSpec",
          "PluginCliCommand",
          "PluginCliOption",
        ],
        firstParty: [
          "Automations",
          "Custom instructions",
          "Docs",
          "GitHub",
          "Keep Awake",
          "Memory",
          "Provider retry",
          "bb connect",
          "Secrets",
          "Tasks",
          "Workflows",
        ],
      },
      {
        id: "agent-tools",
        tagline: "Native tools, skills, and instructions in every session",
        title: "Agent tools & skills",
        summary:
          "Adds tools, skills, and instructions to the agent sessions bb runs. With this, a plugin can:",
        bullets: [
          "Register tools an agent calls the same way it calls bb's built-in tools",
          "Call bb.ui.requestInput from a native tool to return a waiting notice immediately, then deliver the eventual result as a thread message; stopping or deleting the thread, or unloading the plugin, cancels the detached call",
          "Decide per thread which of its tools and skills are available",
          "Append instructions to a session's system prompt as that session starts",
        ],
        apiSymbols: [
          "PluginAgents",
          "PluginAgentToolContext",
          "PluginRowPresentation",
          "PluginRowLabels",
        ],
        firstParty: [
          "Ask User Question",
          "Custom instructions",
          "Memory",
          "bb connect",
          "Workflows",
        ],
      },
      {
        id: "background",
        tagline: "Supervised services and cron schedules",
        title: "Background work",
        summary:
          "Runs code on the bb server when no window is open. With this, a plugin can:",
        bullets: [
          "Register long-running services that bb starts, supervises, and restarts after a failure",
          "Register jobs that run on a cron schedule",
          "Be told to shut down cleanly before it reloads or is disabled",
          "Run one-time setup right after the user installs it with onInstall, for example to pick its own sidebar slots",
        ],
        apiSymbols: ["PluginBackground", "BbPluginApi.onInstall"],
        firstParty: [
          "Automations",
          "Docs",
          "GitHub",
          "Keep Awake",
          "Provider retry",
          "bb connect",
          "Side chat",
          "Tasks",
          "Workflows",
        ],
      },
      {
        id: "wire",
        tagline: "Typed RPC, HTTP & WebSocket routes, realtime push",
        title: "HTTP, WebSocket, RPC & realtime",
        summary:
          "Connects the plugin's own UI, its server code, and outside services. With this, a plugin can:",
        bullets: [
          "Call its server from its UI over RPC, with arguments and results checked against a schema",
          "Publish RPC methods with experimental_discoverable and registration/method experimental_description; other plugins discover implementations and copy their published JSON Schemas using bb plugin rpc inspect",
          "Tell which plugin called an RPC method from the handler's experimental_caller, which is a client for the app, the CLI, and agents",
          "Serve exact-path HTTP and WebSocket routes other systems can call, webhooks included",
          "Publish messages to connected bb windows with bb.realtime.publish and receive them with useRealtime; signals are ephemeral, so observe useRealtimeConnectionState and reconcile server state after reconnecting",
        ],
        apiSymbols: [
          "PluginRpc",
          "PluginRpcMethodContract",
          "ExperimentalPluginRpcHandlersWithContext",
          "ExperimentalPluginRpcHandlerContext",
          "ExperimentalPluginRpcCaller",
          "PluginsArea.experimental_discoverRpc",
          "PluginHttp",
          "PluginRealtime",
          "useRpc",
          "PluginRpcClient",
          "useRealtime",
          "useRealtimeConnectionState",
          "PluginRealtimeConnectionState",
          "ExperimentalPluginWebSocket",
          "ExperimentalPluginWebSocketContext",
          "ExperimentalPluginWebSocketHandler",
          "ExperimentalPluginWebSocketHandlers",
        ],
        firstParty: [
          "Automations",
          "Custom instructions",
          "Docs",
          "GitHub",
          "Inline visualizations",
          "Keep Awake",
          "Memory",
          "Provider retry",
          "bb connect",
          "Side chat",
          "Tasks",
          "Workflows",
        ],
      },
      {
        id: "thread-events",
        tagline: "React when threads start, finish, or fail",
        title: "Thread lifecycle events",
        summary:
          "Runs server code when a thread changes state. With this, a plugin can:",
        bullets: [
          "Subscribe to threads being created, going active or idle, failing, being archived or unarchived, or being deleted",
          "Register handlers before one startup reconciliation because unloaded events are not replayed; avoid polling thread state to detect lifecycle changes",
          "Subscribe to messages being queued behind a wait, dispatching when it clears, or being cancelled before dispatch",
          "Subscribe when a thread receives a pending interaction",
          "Observe debounced experimental_thread.events notifications with the latest sequence and current thread, or experimental_terminal.input without keystroke contents",
          "Observe experimental_host.deleted when a machine is removed, to drop state kept for that machine",
          "Subscribe to a turn failing, with the provider's error and rate-limit windows attached",
          "Respond by sending a notification, asking for a retry, or writing to its own storage",
        ],
        apiSymbols: [
          "PluginEvents",
          "PluginThreadEventPayloads",
          "PluginTurnFailedEvent",
        ],
        firstParty: [
          "Automations",
          "Provider retry",
          "Push notifications",
          "Tasks",
          "Workflows",
        ],
      },
      {
        id: "dispatch-hook",
        tagline: "Decide whether a message may go",
        title: "Dispatch hook",
        summary:
          "Answers the admission checkpoint for ordinary sends, eligible queued messages, and retries before they reach a provider. With this, a plugin can:",
        bullets: [
          "Let a dispatch proceed, queue it with a user-visible reason, or refuse it outright",
          "See the thread, project, machine, prompt and resolved execution tuple before the turn runs",
          "Read each queued message, its author, origin, and originPluginId in queuedMessages, with an empty array for inline attempts",
          "Read the shared initiator category or mixed for a grouped dispatch, and the shared senderThreadId, null when nobody sent it, or mixed",
          "Read the shared origin and originPluginId, each independently mixed when grouped messages differ",
          "Read plugin-owned JSON attached by the composer's submit, including on queued re-attempts",
          "Hold work until a moment it names, then ask core to re-decide every queued message when its condition changes",
          "Let the user override plugin waits with Send now; compaction and an edited message's re-send also bypass this hook",
        ],
        apiSymbols: [
          "PluginHooks",
          "PluginHookSignatures",
          "MessageDispatchHookContext",
          "PluginDispatchEnvironmentIntent",
          "MessageDispatchHookDecision",
        ],
        firstParty: ["Concurrency limit", "Drafts"],
        experimental: true,
      },
      {
        id: "environment-providers",
        tagline: "Provision where a thread runs",
        title: "Environment providers",
        summary:
          "Offers plugin-provisioned places a thread can run, picked like any environment. With this, a plugin can:",
        bullets: [
          "Declare a provider with a required display name, description, and icon, picked in New Thread or bb thread spawn --environment-provider",
          "Use a host glyph, plugin-relative asset, declared icon, or React provider icon slot targeted by required providerKind and providerId",
          "Declare the project facts it consumes in one place — requires.projectCheckout, requires.gitCheckout, requires.gitRemote, requires.projectless — which structurally decides where the picker offers it",
          "Answer availability for a project and machine with available, setup-required, or unavailable; core probes connected machines in the background so pickers hide unsupported ones, caches the answer, and checks it afresh for the selected machine at thread creation",
          "Declare what it needs from the request as a zod inputs schema; bb parses the request with it before the thread exists, publishes it as JSON Schema for the CLI, and hands create the parsed value as inputs",
          "Validate a resolved selection once before thread creation; host-dependent preflight requires connectivity, and create checks conditions that can change afterward",
          "Read the facts as typed values on the create context: host is always non-null, while projectCheckout and gitRemote are non-null exactly when required",
          "Read projectCheckout.experimental_ownsPath to distinguish core clones from user-maintained attachments; core runs environment hooks for owned paths",
          "Render its own control for those inputs beside the picked provider with app.slots.experimental_environmentProviderInputs, reporting either ready inputs or a blocked reason",
          "Use experimental_BranchPicker for a standard branch choice, or compose experimental_useBranches with experimental_useCheckoutState when it needs checkout-aware branch selection",
          "Own the meaning and default of the branch choice: a null BranchPicker value shows Select branch, its label names the menu, and its placeholder replaces the empty trigger",
          "Run one idempotent long create call that returns a created directory or failure; a failed create is terminal and an explicit retry starts a new attempt on the same environment; provider policy exposes only retirement grace and path-key strategy",
          "Let bb run the repo setup hook after an owned-path create and teardown before removal; attached paths skip both hooks; unknown hook outcomes after daemon restart block automatic cleanup",
          "Use core's pathKey for stable resource identity; core records it as the environment instance key",
          "Declare experimental_existingPath to select an existing directory from parsed inputs; core reuses a recorded environment on that machine without creation or changing its lifecycle metadata, and calls create only when no environment exists",
          "Reserve a shared checkout before mutation with create.experimental_claimPath; core holds the host/path claim through attachment or cleanup",
          "Declare restore to give a thread its destroyed environment back on request; it receives the removed environment as previous, while providers without it are never rebuilt and their threads report the environment unavailable",
          "Name a branch the way bb would, from the suggestedBranchName core hands every create, and stream progress with report.step and report.log",
          "Honor create and remove abort signals; core aborts create before asking remove to clean everything under the same path key",
          "Work on the existing enrolled machine carried by the selection, returning the path it produced",
          "Environment input controls receive target: { kind: 'existing-host', hostId } or { kind: 'new-host' }; compositions reuse the underlying control before provisioning, and backend create receives the real host",
          "Register a composition with an explicit display name, description, icon, machineProviderId and environmentProviderId instead of lifecycle callbacks; core creates the machine and uses the concrete environment provider, preserving its checkout ownership",
          "Return an opaque JSON resource handle from a created launch; core keeps up to 16 KiB private and supplies it only to recovery and removal callbacks from the recorded owning plugin",
        ],
        apiSymbols: [
          "PluginEnvironments",
          "PluginEnvironmentProviderDeclaration",
          "PluginEnvironmentProviderRequirements",
          "PluginEnvironmentValidateDecision",
          "PluginEnvironmentProviderInputsRegistration",
          "PluginEnvironmentProviderInputsProps",
          "PluginEnvironmentProviderInputsChange",
          "experimental_BranchPicker",
          "BranchPickerProps",
          "experimental_useBranches",
          "UseBranchesArgs",
          "BranchesState",
          "experimental_useCheckoutState",
          "UseCheckoutStateArgs",
          "CheckoutState",
          "PluginEnvironmentProviderDefinition",
          "PluginEnvironmentProviderInputsSchema",
          "PluginEnvironmentProviderPolicy",
          "PluginEnvironmentProviderValidateContext",
          "PluginEnvironmentProviderAvailabilityContext",
          "PluginEnvironmentProviderAvailability",
          "PluginEnvironmentProviderCreateContext",
          "PluginEnvironmentProviderRestoreContext",
          "PluginEnvironmentProviderCreateResult",
          "PluginEnvironmentProviderProgress",
          "PluginEnvironmentProviderRemoveContext",
          "PluginEnvironmentProviderRemoveResult",
        ],
        firstParty: ["Project checkout", "Personal workspace", "Worktree"],
        experimental: true,
      },
      {
        id: "machine-providers",
        tagline: "Create and own execution machines",
        title: "Machine providers",
        summary:
          "Adds plugin-provisioned machines that compose with environment providers. With this, a plugin can:",
        bullets: [
          "Register bb.experimental_machines with a display name, one-line description, and required glyph, plugin-relative SVG, declared icon, or React icon",
          "Show the provider display name and icon as the kind next to every machine it creates; manually enrolled machines have no kind",
          "Declare automatic retirement for thread-created ephemeral machines; standalone machines remain until explicit removal. Core parses Standard Schema inputs and checks availability and validation before create",
          "Keep secrets in plugin settings because persisted machine inputs are readable by every plugin; pass only non-secret configuration or references",
          "Register an environment composition with machineProviderId and environmentProviderId to create a machine and then use a concrete environment provider; machine registration alone adds no picker option; CLI selects the composition with --environment-provider",
          "Create machines that belong to no project; projects reach a machine later through project sources",
          "Make create idempotent by its host launch key so a restart after enrolment recovers the same machine",
          "Bootstrap over a required MachineExecutor; core Manual setup uses internal enrollment operations; never put credentials in resource JSON or output",
          "Install a daemon for pending enrollment and restart an enrolled identity after snapshot restore",
          "Stream progress on the creating host and honor abort signals for create, suspend, resume and remove",
          "Keep credentials out of report.step and report.log: core persists progress and copies it into thread transcripts; core exposes manual enrollment commands transiently by host ID",
          "Await create.checkpoint(resource) immediately after allocation so cancellation can remove it without waiting for bootstrap",
          "Implement reconcileCleanup to discover and remove uncertain allocations by durable key when no checkpoint exists; remove receives known resources; never create or bootstrap; return failed while allocation intent is unresolved so core retries on its cleanup interval",
          "Await suspend.checkpoint(resource) before destructive cleanup",
          "Await resume.checkpoint(resource) before bootstrap; core fences provider ownership, phase and operation and recovers the same enrollment after restart",
          "Allocation checkpoints are recovery records, not filesystem saves; daemon-connected does not mean agent-ready",
          "Read the current persisted machine resource by host ID with bb.experimental_machines.getResource; reads work across plugins and return null for absent hosts or resources",
          "Own idle timing in the plugin using thread-sequence and terminal-input events plus background schedules",
          "Render one compact machine-inputs control in composed thread creation with app.slots.experimental_machineProviderInputs, reporting a ready non-secret JSON value on mount or a one-sentence blocked reason",

          "Request suspend/resume through the host SDK; calls return the updated host when the tracked operation starts, core coordinates drain, starting thread launches, provisioning environments, and project checkout setup reject suspend with machine_busy, and plugins own idle policy",
          "Read maintenance state and lifecycle failures from each host's lifecycle phase and message",
          "Call hosts.experimental_reconcile from plugin-owned maintenance to enforce core’s suspended state through the provider; active and transitional states are unchanged, the call returns after acceptance; poll host status for completion, and core does not poll. Suspend and resume must be idempotent: preserve stopped resources and reuse running compute. Request new pauses with experimental_suspend",
          "Await suspend.checkpoint(resource) to persist opaque resource state before termination; schedule vendor maintenance in the plugin using bb.background.schedule and bb.sdk.hosts.experimental_suspend",
          "Optionally declare suspend and resume together; plugins own idle timing and core coordinates transitions",
          "Return an opaque JSON resource that core persists and passes back to lifecycle operations; never include credentials",
          "Return a required readable machine name from create",
          "Treat a failed create as terminal and retry vendor API hiccups inside the create call",
        ],
        apiSymbols: [
          "PluginMachines",
          "PluginBbSdk.hosts.experimental_create",
          "PluginBbSdk.hosts.experimental_getEnrollmentCommand",
          "PluginBbSdk.hosts.experimental_listProviders",
          "PluginBbSdk.hosts.experimental_suspend",
          "PluginBbSdk.hosts.experimental_reconcile",
          "PluginBbSdk.hosts.experimental_resume",
          "PluginBbSdk.hosts.experimental_retryCleanup",
          "PluginMachines.getResource",
          "MachineExecutorRequest",
          "MachineExecutor",
          "MachineBootstrapRequest",
          "MachineBootstrapApi",
          "PluginMachineProviderDeclaration",
          "PluginMachineValidateDecision",
          "PluginMachineProviderInputsRegistration",
          "PluginMachineProviderInputsProps",
          "PluginMachineProviderInputsChange",
          "PluginMachineProviderDefinition",
          "PluginMachineProviderInputsSchema",
          "PluginMachineProviderAvailability",
          "PluginMachineProviderValidateContext",
          "PluginMachineProviderCreateContext",
          "PluginMachineProviderCreateResult",
          "PluginMachineProviderLifecycleContext",
          "PluginMachineProviderProgress",
          "PluginMachineProviderResourceResult",
          "PluginMachineProviderResource",
          "PluginMachineProviderRemoveResult",
        ],
        firstParty: ["Modal Sandbox [Experimental]"],
        experimental: true,
      },
      {
        id: "server-access",
        tagline: "Connect machines to their server",
        title: "Machine server access",
        summary:
          "Registers server access for enrolment and ongoing machine runtime requests. With this, a plugin can:",
        bullets: [
          "Register bb.experimental_serverAccess with picker copy, availability (including an optional public serverUrl), idempotent acquire and release",
          "Call recheck when access is gained or lost; refreshed configuration checks availability for Machines settings, manual setup and creation banners",
          "Return { id, serverUrl, headers? }; machines attach headers to all server requests without provider-specific redemption",
          "Choose a General default; core retains the selection for each machine; automatic selection uses the first registered provider, or direct when none are registered",
          "Use the Server URL reachable by machines setting or BB_EXTERNAL_URL fallback; the URL is not a reachability guarantee",
          "Return { status: 'failed', message } for a user-safe recovery message; persist acquisition intent and keep credentials in secret storage; release receives key, hostId and a nullable grantId to reconcile interrupted acquisitions before enrollment",
        ],
        apiSymbols: [
          "PluginServerAccess",
          "ServerAccessProviderDeclaration",
          "ServerAccessGrant",
        ],
        firstParty: ["bb connect"],
        experimental: true,
      },
      {
        id: "host-workers",
        tagline: "Run code on enrolled machines",
        title: "Host workers",
        summary:
          "Runs the plugin's code on an enrolled machine, not only on the bb server. With this, a plugin can:",
        bullets: [
          "Ship a Node entry point bb starts on demand on the machine it calls",
          "Call that worker from its server code over typed RPC",
          "Do work that has to happen on the machine itself, such as watching files or holding a wake lock",
          "Declare desired loopback ports once and let bb deliver retained declarations when an enrolled machine reconnects",
          "Kill whatever is still running under a directory it is about to delete, SIGTERM then SIGKILL, so a torn-down workspace leaves nothing behind",
          "Spawn host-local commands with a sanitized inherited environment",
        ],
        apiSymbols: [
          "PluginHosts",
          "experimental_killProcessesWithCwdUnder",
          "experimental_sanitizeInheritedChildProcessEnv",
          "ExperimentalSanitizeInheritedChildProcessEnvArgs",
          "experimental_spawnPortableOutputProcess",
        ],
        firstParty: [
          "Project checkout",
          "Keep Awake",
          "Personal workspace",
          "bb connect",
          "Worktree",
        ],
        experimental: true,
      },
      {
        id: "storage",
        tagline: "Namespaced KV plus your own SQLite",
        title: "Storage",
        summary:
          "Stores the plugin's data on the bb server. With this, a plugin can:",
        bullets: [
          "Get a key-value store for small values such as flags and cursors",
          "Store internal credentials in plugin KV without exposing settings fields",
          "Get its own SQLite database, with migrations, for larger or relational data",
          "Reject a changed or reused migration number before it can hide a schema change",
          "Read and write only its own namespace; other plugins cannot see it",
        ],
        apiSymbols: ["PluginStorage"],
        firstParty: [
          "Automations",
          "Custom instructions",
          "Docs",
          "GitHub",
          "Keep Awake",
          "Memory",
          "bb connect",
          "Side chat",
          "Tasks",
          "Workflows",
        ],
      },
      {
        id: "bb-sdk",
        tagline: "Create threads and projects from plugin code",
        title: "The bb SDK",
        summary:
          "Calls bb's own API from the plugin's server code. With this, a plugin can:",
        bullets: [
          "Create threads, send messages to them, and manage projects",
          "Spawn or fork with lifecycleOwnerThreadId to archive/delete a dependent with a live owner across projects; ownership is immutable, independent of sidebar parents and supports different hosts/environments. Thread responses return the owner or null. Unarchive owner first; Stop does not cascade",
          "List machines and suspend, resume, or remove provider-managed machines",
          "Read nullable threadStorageRootPath with sdk.hosts.get from the latest daemon session, even offline or without live threads; null before the first reported session",
          "Explicitly clean up unused provider-managed environments with sdk.environments.experimental_cleanup, overriding retention/keep policy and backoff; live threads prevent cleanup, already-removed environments succeed, and lifecycle fields report completion",
          "Read recorded context usage with sdk.threads.context({ threadId }); usage is null when unavailable, and its snapshot is present only when the latest measurement includes a breakdown",
          "Page through every user prompt in history, newest first, with sdk.experimental_promptHistory.list; each entry carries its project and thread, and nextCursor continues from where the page ended",
          "Reach the same operations the [bb CLI](cli) and the bb UI use",
          "Have the threads it creates attributed back to the plugin",
          "Read the server's loopback URL, public app URL, and data directory when it needs server facts",
          "Read or toggle plugin safe mode with sdk.plugins.experimental_getSafeMode and experimental_setSafeMode; safe mode stops every installed plugin not included with bb and restores the enabled ones when it ends, reporting any that fail to start",
        ],
        apiSymbols: [
          "BbPluginApi",
          "PluginServerApi",
          "HostsArea.get",
          "ExperimentalPromptHistoryArea.list",
          "EnvironmentsArea.experimental_cleanup",
          "PluginsArea.experimental_getSafeMode",
          "PluginsArea.experimental_setSafeMode",
        ],
        firstParty: [
          "Automations",
          "Docs",
          "GitHub",
          "Inline visualizations",
          "Keep Awake",
          "Provider retry",
          "Push notifications",
          "Secrets",
          "Side chat",
          "Tasks",
          "Workflows",
        ],
      },
      {
        id: "thread-plugin-metadata",
        tagline: "Keep plugin data with a thread",
        title: "Thread plugin metadata",
        summary:
          "Stores namespaced plugin JSON for a thread without automatically exposing it to the model. With this, a plugin can:",
        bullets: [
          "Seed its namespace when spawning a thread or explicitly when forking one",
          "Read and atomically patch any namespace allowed by ordinary thread access",
          "Receive only its own deep-frozen namespace in bb.agents.configure",
          "Keep up to 256 KiB of JSON per namespace; a patch that would exceed it fails and leaves the namespace unchanged",
        ],
        apiSymbols: [
          "PluginBbSdk",
          "PluginAgentConfigurationContext",
          "ReadonlyJsonValue",
          "BbPluginApi",
        ],
      },
      {
        id: "desktop-browsers",
        title: "Desktop browser control",
        tagline: "Use your automation tool on BB-owned tabs",
        summary:
          "Controls a selected desktop window through bb.sdk.experimental_desktopBrowsers. With this, a plugin can:",
        bullets: [
          "Discover instances on an explicit host and create thread-owned tabs in the BB browser profile",
          "Acquire expiring control; reveal the first tab and new CDP pages only in the already focused thread, without activating the desktop window. Controlled tabs carry the BB browser profile's signed-in cookies",
          "Give a worker on that host a private, scoped CDP WebSocket connection for DevBrowser or agent-browser",
          "Capture or reveal a tab and release control while preserving the tab and its login",
          "Observe changed tab and control state with a disposable two-second polling subscription; report disconnect errors",
          "List known browsers and schema-detected Chromium/Firefox profiles belonging to registered browsers on the desktop host; use the returned source ID to copy a profile's signed-in cookies into the BB browser profile",
        ],
        apiSymbols: [
          "ExperimentalDesktopBrowsersArea",
          "ExperimentalDesktopBrowserScope",
          "ExperimentalDesktopBrowserLease",
          "ExperimentalDesktopBrowserCreateInput",
          "ExperimentalDesktopBrowserAcquireInput",
          "ExperimentalDesktopBrowsersArea.listImportSources",
          "ExperimentalDesktopBrowsersArea.importCookies",
        ],
        firstParty: ["Browser Automation"],
        experimental: true,
      },
      {
        id: "ai-services",
        tagline: "Write bb's titles, commit messages, and transcripts",
        title: "AI services",
        summary:
          "Lets a plugin answer bb's helper tasks with plain functions — a prompt in and text out for thread titles and commit messages, and audio in and text out for the microphone button. With this, a plugin can:",
        bullets: [
          "Write thread titles and commit messages with any model or API the plugin chooses",
          "Transcribe voice input for the microphone button in the prompt box",
          "Appear as a choice per task in Settings → AI services, with a status line that says how to make it ready",
          "Participate in Automatic after bb cloud, ordered by plugin ID and service ID",
        ],
        apiSymbols: [
          "PluginAiServices",
          "PluginAiServiceDeclaration",
          "PluginAiServiceStatus",
        ],
        firstParty: ["Codex provider", "bb cloud AI"],
        experimental: true,
      },
      {
        id: "host-components",
        tagline: "Embed bb's chat and prompt box",
        title: "Host components",
        summary:
          "Renders bb's chat, prompt box, pickers, file content, links, and shared app icons inside plugin pages. With this, a plugin can:",
        bullets: [
          "Embed the thread view and the new-thread prompt box as components",
          "Seed experimental_NewThreadComposer or navigate.toCompose with initialPrompt containing @thread:<id>, @project:<id>, or @section:<id> to create mention pills with host-resolved labels; composer seeds preserve non-empty drafts",
          "Render message text with the same Markdown renderer bb uses",
          "Embed experimental_ProviderModelPicker and experimental_PermissionModePicker with the host's provider defaults, capabilities, and machine permission ceiling",
          "Render supplied code and diffs with experimental_SourceCode and experimental_Diff, or use experimental_useCodeTheme to theme an embedded editor",
          "Use UrlLink or useBbNavigate().openUrl for bb's browser preference; use experimental_FileLink for workspace, host, or thread-storage targets with optional line or range locations",
          "Open the same live-file targets in bb's preview or the preferred external editor with experimental_openFilePreview and experimental_openFileExternally",
          "Resolve document links and images beside a workspace or thread-storage file with Markdown.experimental_document",
          "Inherit bb's styling, so embedded UI matches the rest of the app",
          "Register inline React artwork with app.experimental_icons.register({ name, component }); namespacing is recommended, but any plugin can use any name",
          "Add names or override built-in app icons; conflicts between plugins use the first plugin id in lexical order and warn, while duplicate names within one plugin reject setup",
          "Render experimental_ProviderIcon with required providerKind (agent, machine, environment), provider={provider}, and optional fallback (Code by default). Pass an existing provider record: it reads id, logoUrl, icon, and strings.iconTint, resolving the matching kind/id slot override, then legacy unscoped overrides, then declared artwork. It fetches no metadata. Marks are decorative by default; pass aria-label for a meaningful standalone image",
          "Provider icons update on plugin load/reload/unload; throwing or recursive overrides fall back to supplied artwork. Use the same component for agent, machine, and environment providers",
          "Use the same icon names in experimental_Icon and host-rendered icon fields: registered React artwork wins over built-in names, followed by namespaced <pluginId>/<name> assets from bb.branding.experimental_icons. Missing names use the surface's fallback",
          "Explicit resolved icons take precedence over bb.branding.icon for mentions, message actions, navigation panels, fixed tabs, panel launchers and their opened tabs, and legacy sidebar-footer actions; omitted or unknown names fall back to plugin branding, then Zap. Plugin identity in Tools and Settings keeps its branding. Composer menu items and draft-row status continue using their supplied icons",
          "Return nothing from icon registration: bb replaces React artwork on reload and removes it on unload. Declared SVG icons need no app bundle and remain available while the plugin is stopped; React artwork receives className and should use currentColor",
          "Load the same registrations in web, desktop, and mobile's web app; manage their plugin through bb plugin build, install, reload, and remove",
        ],
        apiSymbols: [
          "experimental_Icon",
          "experimental_ProviderIcon",
          "ExperimentalProviderIconProps",
          "ExperimentalIconProps",
          "ExperimentalIconRegistration",
          "ExperimentalAppIcons",
          "PluginAppBuilder.experimental_icons",
          "ThreadChat",
          "Markdown",
          "MarkdownProps.experimental_document",
          "experimental_NewThreadComposer",
          "experimental_ProviderModelPicker",
          "ExperimentalProviderModelPickerProps",
          "experimental_PermissionModePicker",
          "ExperimentalPermissionModePickerProps",
          "experimental_SourceCode",
          "SourceCodeProps",
          "experimental_Diff",
          "DiffProps",
          "experimental_useCodeTheme",
          "PluginCodeThemeState",
          "UrlLink",
          "UrlLinkProps",
          "experimental_FileLink",
          "ExperimentalFileLinkProps",
          "ExperimentalLiveFileTarget",
          "ExperimentalFileLocation",
          "ExperimentalFileOpenOptions",
          "BbNavigate.openUrl",
          "BbNavigate.experimental_openFilePreview",
          "BbNavigate.experimental_openFileExternally",
        ],
        firstParty: ["Side chat", "Provider usage", "Tasks"],
      },
      {
        id: "testing",
        tagline: "Unit-test every surface without a running bb",
        title: "Testing harnesses",
        summary:
          "Tests the plugin without a running bb. With this, a plugin can:",
        bullets: [
          "Run its server code against an in-process fake of the bb server",
          "Render its UI slots under vitest and jsdom",
          "Drive its host worker with no host daemon running",
        ],
        apiSymbols: [
          "createFakePluginHost",
          "renderSlot",
          "createFakeSdk",
          "experimental_createHostEntryHarness",
        ],
        firstParty: [
          "Ask User Question",
          "Automations",
          "Custom instructions",
          "Docs",
          "GitHub",
          "Inline visualizations",
          "Keep Awake",
          "Memory",
          "Provider retry",
          "bb connect",
          "Secrets",
          "Side chat",
          "Tasks",
          "Workflows",
        ],
      },
    ],
  },
];

export const GROUP_BY_SURFACE_ID: ReadonlyMap<
  string,
  { id: SurfaceGroup["id"]; title: string }
> = new Map(
  SURFACE_GROUPS.flatMap((group) =>
    group.surfaces.map(
      (surface) => [surface.id, { id: group.id, title: group.title }] as const,
    ),
  ),
);

export const SURFACES_BY_ID: ReadonlyMap<string, PluginSurface> = new Map(
  SURFACE_GROUPS.flatMap((group) =>
    group.surfaces.map((surface) => [surface.id, surface] as const),
  ),
);
